### DISCUSSION TITLE
ESP-IDF with Arduino as a Component Undefined Reference (to Module)

### DISCUSSION THREAD

**Discussion by leemind** [jgromes/RadioLib#1393] [Q&A]
I'm pulling my hair out with this one.  I am trying to wean myself off the Arduino platform (I was using it with PlatformIO, but the latest spat between PIO and Espressif means I want to go native)

ESP32S3 (custom board)
SX1268
ESP-IDF & Arduino as a component

I have incorporated RadioLib as a managed component in IDF
idf_component.yml:

```
 ## IDF Component Manager Manifest File
dependencies:
  ## Required IDF version
  idf:
    version: '>=4.1.0'
  # # Put list of dependencies here
  # # For components maintained by Espressif:
  # component: "~1.0.0"
  # # For 3rd party components:
  # username/component: ">=1.0.0,<2.0.0"
  # username2/component2:
  #   version: "~1.0.0"
  #   # For transient dependencies `public` flag can be set.
  #   # `public` flag doesn't have an effect dependencies of the `main` component.
  #   # All dependencies of `main` are public by default.
  #   public: true
  espressif/arduino-esp32: ^3.1.1
  espressif/esp-dsp: '*'
  joltwallet/littlefs: ==1.16.2
  h2zero/esp-nimble-cpp: ^2.1.0
  jgromes/radiolib: ^7.1.2
```

I don't think you need anything more in CMakeLists.txt but here is the one in main:
```
idf_component_register(
    SRCS "main.cpp" "display.cpp" "ble_init.cpp" "ICM42688.cpp" "button.cpp"
    INCLUDE_DIRS "include"
    REQUIRES arduino-esp32 bt nvs_flash PNGdec TFT_eSPI Fusion app_update bmp280 i2cdev ArduinoJson
)
littlefs_create_partition_image(storage ../littlefs FLASH_IN_PROJECT)
```

but when the linker tries to link it all together it fails to find "Module" from this line
```
SX1268 radio = new Module(RADIO_CS_PIN, RADIO_DIO1_PIN, RADIO_RST_PIN, RADIO_DIO0_PIN);
```

with the error 
```
/Users/david/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20240530/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(main.cpp.obj):(.literal._Z41__static_initialization_and_destruction_0v+0x18): undefined reference to `_ZN6ModuleC1Emmmm'
/Users/david/.espressif/tools/xtensa-esp-elf/esp-13.2.0_20240530/xtensa-esp-elf/bin/../lib/gcc/xtensa-esp-elf/13.2.0/../../../../xtensa-esp-elf/bin/ld: esp-idf/main/libmain.a(main.cpp.obj): in function `_Z41__static_initialization_and_destruction_0v':
/Users/david/Development_Local/Rubble/RubbleDeviceIDF/main/main.cpp:109:(.text._Z41__static_initialization_and_destruction_0v+0x42): undefined reference to `_ZN6ModuleC1Emmmm'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

I'm sure I must be missing something in one of the cmake files or the idf_component files but I have no idea what.  The other managed components work just fine.

Any ideas?
